# Generated by Django 3.1.5 on 2021-01-31 07:37

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('layout', models.CharField(choices=[('0', 'big circle image')], default='0', max_length=1)),
                ('transitionIn', models.CharField(choices=[('0', 'slide in')], default='0', max_length=1)),
                ('transitionOut', models.CharField(choices=[('0', 'slide out')], default='0', max_length=1)),
                ('position', models.CharField(choices=[('0', 'left bottom'), ('1', 'left top'), ('2', 'right bottom'), ('3', 'right top')], default='0', max_length=1)),
                ('xOffset', models.CharField(default='10px', max_length=20)),
                ('yOffset', models.CharField(default='20px', max_length=20)),
                ('backgroundColor', colorfield.fields.ColorField(default='#ffffff', max_length=18)),
                ('headingColor', colorfield.fields.ColorField(default='#000000', max_length=18)),
                ('textColor', colorfield.fields.ColorField(default='#333333', max_length=18)),
                ('customCSS', models.TextField(verbose_name='custom css')),
            ],
        ),
    ]
