# Generated by Django 3.1.5 on 2021-01-31 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proofs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='proofs')),
            ],
        ),
        migrations.AlterField(
            model_name='campain',
            name='customCSS',
            field=models.TextField(blank=True, verbose_name='custom css'),
        ),
    ]
