# Generated by Django 3.1.5 on 2021-01-31 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210131_0956'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proof',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='proofs')),
                ('title', models.CharField(max_length=80)),
                ('time', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=200)),
                ('logo', models.ImageField(upload_to='logos')),
            ],
        ),
        migrations.DeleteModel(
            name='Proofs',
        ),
        migrations.AddField(
            model_name='campain',
            name='displayTime',
            field=models.IntegerField(default=10, verbose_name='display time'),
        ),
        migrations.AddField(
            model_name='campain',
            name='hideTime',
            field=models.IntegerField(default=4, verbose_name='hide time'),
        ),
        migrations.AddField(
            model_name='campain',
            name='isActive',
            field=models.BooleanField(default=False, verbose_name='active'),
        ),
        migrations.AddField(
            model_name='campain',
            name='startDelay',
            field=models.IntegerField(default=5, verbose_name='start delay'),
        ),
        migrations.AddField(
            model_name='campain',
            name='url',
            field=models.URLField(default='ms-global.co.il', verbose_name='url'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campain',
            name='proofs',
            field=models.ManyToManyField(to='core.Proof'),
        ),
    ]
