# Generated by Django 3.1.5 on 2021-01-31 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210131_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proof',
            name='logo',
            field=models.ImageField(blank=True, upload_to='logos'),
        ),
        migrations.AlterField(
            model_name='proof',
            name='time',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
