# Generated by Django 3.1.6 on 2021-02-03 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210202_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campain',
            name='proofs',
            field=models.ManyToManyField(related_name='campains', to='core.Proof'),
        ),
    ]
