# Generated by Django 3.1.6 on 2021-02-03 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210203_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campain',
            name='proofs',
            field=models.ManyToManyField(related_name='camp', to='core.Proof'),
        ),
    ]
