# Generated by Django 3.1.6 on 2021-02-03 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210203_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='campain',
            name='direction',
            field=models.CharField(choices=[('l', 'left to right'), ('r', 'right to left')], default='l', max_length=1),
        ),
    ]
