# Generated by Django 3.1.6 on 2021-02-04 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20210203_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campain',
            name='transitionIn',
            field=models.CharField(choices=[('slide_right', 'slide in right'), ('slide_left', 'slide in left'), ('slide_bottom', 'slide in bottom'), ('slide_up', 'slide in up')], default='slide_right', max_length=20),
        ),
        migrations.AlterField(
            model_name='campain',
            name='transitionOut',
            field=models.CharField(choices=[('slide_right', 'slide out right'), ('slide_left', 'slide out left'), ('slide_down', 'slide out down'), ('slide_up', 'slide out up')], default='slide_right', max_length=20),
        ),
    ]
