# Generated by Django 3.1.6 on 2021-02-04 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20210204_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proof',
            name='message',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='proof',
            name='title',
            field=models.CharField(max_length=250),
        ),
    ]
