# Generated by Django 3.1.6 on 2021-02-04 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_proof_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proof',
            old_name='starts',
            new_name='stars',
        ),
    ]
