# Generated by Django 3.1.6 on 2021-02-08 08:12

import core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20210204_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campain',
            name='backgroundColor',
            field=core.models.ColorField(default='#ffffff', max_length=10),
        ),
        migrations.AlterField(
            model_name='campain',
            name='headingColor',
            field=core.models.ColorField(default='#000000', max_length=10),
        ),
        migrations.AlterField(
            model_name='campain',
            name='textColor',
            field=core.models.ColorField(default='#333333', max_length=10),
        ),
    ]
