# Generated by Django 3.1.6 on 2021-02-07 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubPlant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.SmallIntegerField(verbose_name='number of domains')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='price')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isActive', models.BooleanField(verbose_name='is active')),
                ('isCanceled', models.BooleanField(verbose_name='is cancle')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('created_at', models.DateTimeField()),
                ('last_updated_on', models.DateTimeField()),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.subplant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
