# Generated by Django 3.1.6 on 2021-02-07 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubPlantFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('subPlant', models.ManyToManyField(related_name='features', to='subscriptions.SubPlant')),
            ],
        ),
    ]
